core/urls.py
from django.conf.urls import patterns, url
from core.views import *


urlpatterns = patterns('',
    url(r'^$', home, name='home'),
    url(r'^buy/(?P<product_id>\w+)$', buy, name='buy'),
    url(r'^checkout/$', checkout, name='checkout'),
    url(r'^process-order/', process_order, name='process_order'),
)

django_pesapal/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'django_pesapal.views.home', name='home'),
    url(r'^pesapal/', include('core.urls', namespace='pesapal')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^pesapal/admin/', include(admin.site.urls)),
)

core/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Pesapal(models.Model):
    """
    Model to hold pesapal callback info
    """
    #<PENDING|COMPLETED|FAILED|INVALID>
    PESAPAL_STATUS_CHOICES = (
                ('PENDING', 'Pending'),
                ('COMPLETED', 'Completed'),
                ('FAILED', 'Failed'),
                ('INVALID', 'Invalid'),
            )
    tracking_id = models.CharField(max_length=50, verbose_name='Pesapal Transaction Tracking ID')
    reference = models.CharField(max_length=50, verbose_name='Pesapal Merchant Reference')
    status = models.CharField(max_length=9, choices=PESAPAL_STATUS_CHOICES, default='PENDING')

    class Meta:
        verbose_name = 'Pesapal Payment'
        verbose_name_plural = 'Pesapal Payments'
        
        def __unicode__(self):
            return 'Payment %s for '%(self.status,self.reference)

core/views.py
# Create your views here.
import requests
import datetime
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib.auth.models import User
from pymongo import MongoClient
from bson.objectid import ObjectId
import  pesapal
from django_pesapal.settings import mongo_host, mongo_port
from core.models import Pesapal

products_db = MongoClient(mongo_host, mongo_port)['sasa']['products']
def home(request):
    """
    Home page for django-pesapal example
    """
    products = []
    for item in products_db.find(limit=3):
       product = {
                   'name': item['name'],
                   'price': item['price'],
                   'thumbnail': item['thumbnail'],
                   'preview': item['preview'],
                   'product_id': item['_id']
               }
       products.append(product)
    return render_to_response('home.html', {'products': products}, context_instance=RequestContext(request))


def buy(request,product_id):
    """
    Buy product with _id = product_id
    """
    item = products_db.find_one({'_id': ObjectId(product_id)})
    product = {
                'name': item['name'],
                'price': item['price'],
                'thumbnail': item['thumbnail'],
                'preview': item['preview'],
                'product_id': item['_id']
            }
    

    return render_to_response('buy.html',
            {
                'product': product,
            },
            context_instance=RequestContext(request)
        )


def checkout(request):
    """
    """
    delivery_fee = 0 
    if request.method == 'POST':
        product_id = request.POST.get('product_id', '')
        temp_cost = request.POST.get('cost',0)
        cost = int(temp_cost.split('.')[0])
        delivery_option = request.POST.get('delivery','')
        if delivery_option == 'd':
            delivery_fee = 300
            total_cost = cost + delivery_fee 
        else:
            total_cost = cost

        client = pesapal.PesaPal('uvzyNdMvjn6Ir4id+zwcUNT7bKOsp+wY','fXFK6owbt2B00Yq6JscpvKmDm6o=',True)
        request_data = {
            'Amount': str(total_cost),
            'Description': 'Purchase of jewelry from shopsoko.com',
            'Type': 'MERCHANT',
            'Reference': str(datetime.datetime.now()),
            'Email': 'info@shopsoko.com'
            }
        post_params = {
            'oauth_callback': 'http://staging.shopsoko.com/pesapal/process-order'
            }
        pesapal_request = client.postDirectOrder(post_params, request_data)
        return render_to_response('checkout.html', {
                'total_cost': total_cost,
                'cost': cost,
                'delivery_fee': delivery_fee,
                'iframe_url': pesapal_request.to_url()
                }, context_instance=RequestContext(request))


def process_order(request):
    """
    Handle the callback from pesapal
    """
    tracking_id = request.GET.get('pesapal_transaction_tracking_id', '')
    reference = request.GET.get('pesapal_merchant_reference', '')
    #save this data to a model
    errors = ''
    msg = ''
    if tracking_id and reference:
        params = {
                    'pesapal_merchant_reference': reference,
                    'pesapal_transaction_tracking_id': tracking_id
                 }
        client = pesapal.PesaPal('uvzyNdMvjn6Ir4id+zwcUNT7bKOsp+wY','fXFK6owbt2B00Yq6JscpvKmDm6o=',True)
        pesapal_request = client.queryPaymentStatus(params)
        url = pesapal_request.to_url()
        print url
        pesapal_response = requests.get(url)
        pesapal_response_data = pesapal_response.text
        print pesapal_response_data
        pesapal_status = pesapal_response_data.split('=')[1]
        if pesapal_status == 'COMPLETED':
            msg = 'Transaction was successful'
        else:
            msg = 'Transaction status is %s'%(pesapal_status)
        p_ref = Pesapal(tracking_id=tracking_id, reference=reference, status=pesapal_status)
        p_ref.save()
    else:
        errors ='You broke our servers :-('
    return render_to_response('process-order.html', {'errors': errors, 'msg': msg}, context_instance=RequestContext(request))

core/templates/buy.html
{% extends "base.html" %}
{% block css %}
{% endblock%}
{% block javascript %}
    $("input[type='radio']").change(function(){
        if($(this).val()=="d"){
            $("#location").show();
        }
        else{
            $("#location").hide(); 
        }
    });
{% endblock %}
{% block title %} Buy {{ product.name }} {% endblock %}
{% block page-content %}
    <div class="images_stream span7 offset2">
        <div class="product_item">
            <div class="product_name">
                {{ product.name }}
            </div>
            <br />
            <br />
            <img src="{{ product.thumbnail}}" class="image-polaroid" style="height: 368px;">
            <br />
            <br />
            <div class="product_bottom">
                <div class="product_price">
                    KES {{ product.price }}
                </div>
            </div>
            
        </div>
        <form action="{% url  'pesapal:checkout' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="product_id" value="{{ product.product_id }}"/>
            <input type="hidden" name="cost" value="{{ product.price }}"/>

            <legend>Payment and Delivery</legend>
            <br />
            Pickup and delivery available. Our delivery fee is <span class="label label-info">KES.300.00</span> with a minimum order of <span class="label label-info">KES 1500.00</span>
            <br />
            <br />

            <fieldset>
                <h4>Delivery option</h4>
                <p>
                    Shopsoko allows orders for both pickup and delivery. Please select one of the options below:
                </p>
                <div class="control-group">
                    <div class="controls">
                        <label class="radio">
                            <input type="radio" name="delivery" value="d" >
                            I want my order Delivered to me
                        </label>
                        <br />
                        <input type="text" style="display: none;" class="input-xxlarge" name="location" id="location" placeholder="Please provide your location details" />

                    </div>
                </div>
                <div class="control-group">
                    <div class="controls">
                        <label class="radio">
                            <input type="radio" name="delivery" value="p" >
                                I want to Pickup my order from the Soko Office ( 707 Muchai drive, off Ngong Road )
                        </label>
                    <div>
                </div>
                        

                <div class="control-group">
                    <div class="controls">
                        <input type="submit" value="Submit" class="btn btn-success" />
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock %}

core/templates/checkout.html
{% extends "base.html" %}
{% block css %}
{% endblock%}
{% block javascript %}
{% endblock %}
{% block title %} Buy {{ product.name }} {% endblock %}
{% block page-content %}
    <div class="images_stream span7 offset2">
        <div class="product_item">
            <table class="table table-bordered">
                <tr>
                    <td>Items total</td>
                    <td> KES {{ cost }} </td>
                </tr>
                {% if delivery_fee %}
                    <tr>
                        <td>Deliver Fee</td>
                        <td> KES 300</td>
                    </tr>
                {% else %}
                    <tr>
                        <td>Deliver Fee</td>
                        <td> KES 0</td>
                    </tr>    
                {% endif %}
                <tr>
                    <td>Sum Total</td>
                    <td> KES {{ total_cost }} </td>
                </tr>
            </table>
        </div>
        <br />
        <iframe src="{{ iframe_url}}" width="100%" height="620px" scrolling="auto" frameBorder="0"> <p>Unable to load the payment page</p></iframe>
    </div>
{% endblock %}

core/templates/home.html
{% extends "base.html" %}
{% block css %}
{% endblock%}
{% block javascript %}
{% endblock %}
{% block title %} Home {% endblock %}
{% block page-content %}
    <div class="images_stream span7 offset2">
        {% for product in products %}
            <div class="product_item">
                <div class="product_name">
                    {{ product.name }}
                </div>
                <img src="{{ product.thumbnail}}" class="image-polaroid" style="height: 368px;">
                <br />
                <br />
                <div class="product_bottom">
                    <div class="product_price">
                        KES {{ product.price }}
                    </div>
                    <div class="btn_buy">
                        <a href="{% url 'pesapal:buy' product.product_id %}" class="btn btn-primary" >Buy</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

core/templates/process-order.html
{% extends "base.html" %}
{% block css %}
{% endblock%}
{% block javascript %}
{% endblock %}
{% block title %} Process Order {% endblock %}
{% block page-content %}
    <div class="images_stream span7 offset2">
        <div class="product_item">
            {% if errors %}
                <h1>{{ errors }}</h1>    
            {% else %}
                <div class="product_name">
                    {{msg}}
                </div>
            {% endif %}
            
    </div>
{% endblock %}

django_pesapal/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %} {% endblock %} | ShopSoko </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="shortcut icon" href="http://staging_static.s3.amazonaws.com/images/favicon.png">
    <!-- Le styles -->
    <link href="{{STATIC_URL}}css/bootstrap.css" rel="stylesheet">
    <link href="{{STATIC_URL}}css/django-pesapal.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
      
    {% block css %}{% endblock %}
    </style>
    <link href="{{STATIC_URL}}css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
  </head>

  <body class="body">

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="{% url 'pesapal:home' %}">Django Pesapal</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
                <li class="active"><a href="{% url 'pesapal:home' %}">Django Pesapal</a></li> 
            </ul>
            <ul class="nav pull-right">
                <li><a href="">About</a></li>
              <li class="divider-vertical"></li>
              <li><a href="">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div id="page-content">
          {% block page-content %}
            
          {% endblock %}
      <div class="clearfix"></div>
    </div>
    <div class="modal-footer span7 offset2">
        
        &copy django-pesapal  2013

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap.js"></script>
    <script type="text/javascript">
        {% block javascript %}{% endblock %}
    </script>

  </body>
</html>